"""
Pydantic schemas for the Multimodal Semantic Reasoning Layer (VLM).
Ensures strictly typed, audit-ready grounded evidence contexts and structured interpretations.
"""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class GroundedEvidenceItem(BaseModel):
    source: str = Field(..., description="Agent or module providing the evidence (e.g. changeformer, building_segmenter, sentinel1, sentinel2, sam)")
    modality: str = Field(..., description="Modality (e.g. optical_bitemporal, sar, multispectral, geometric)")
    findings: Dict[str, Any] = Field(default_factory=dict, description="Verified numerical and categorical findings")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Exact quantitative measurements (counts, percentages, indices)")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Evidence item confidence")


class GroundedEvidenceContext(BaseModel):
    """
    Immutable, sanitized structured evidence package passed to the VLM.
    Protects against prompt injection and enforces that the VLM only sees
    verified quantitative facts and data capabilities.
    """
    query: str = Field(..., description="Sanitized user query")
    task: str = Field(..., description="Planner task type (e.g. urban_change, flood_impact, generic_change)")
    data_capability: Dict[str, Any] = Field(default_factory=dict, description="Data capability constraints (e.g. rgb_only, has_temporal, has_sar)")
    evidence: List[GroundedEvidenceItem] = Field(default_factory=list, description="Authoritative verified evidence items")
    verification: Dict[str, Any] = Field(default_factory=dict, description="Verification engine outcome (passed, passed_with_warnings, failed, checks)")
    confidence: Dict[str, Any] = Field(default_factory=dict, description="Confidence breakdown (overall, consistency, sensor_reliability, etc.)")
    uncertainty: List[Dict[str, Any]] = Field(default_factory=list, description="Explicit uncertainty flags and severity")
    spatial_metadata: Dict[str, Any] = Field(default_factory=dict, description="Known georeferenced coordinates or ROI, strictly no invented locations")


class SemanticInterpretation(BaseModel):
    """
    Structured response generated by the VLM layer.
    Enforces strict separation of observation vs interpretation vs conclusion.
    """
    summary: str = Field(..., description="Concise, verified high-level semantic summary")
    observations: List[str] = Field(default_factory=list, description="Strictly observed quantitative facts directly from verified evidence")
    interpretation: List[str] = Field(default_factory=list, description="Contextual interpretation of spatial patterns and modality relationships")
    conclusion: str = Field(..., description="Confidence-qualified conclusion. Must explicitly state verification limitations if unverified")
    evidence_used: List[str] = Field(default_factory=list, description="List of source agents/evidence keys referenced")
    contradictions: List[str] = Field(default_factory=list, description="Explicitly noted conflicting or diverging modalities if present")
    uncertainties: List[str] = Field(default_factory=list, description="Acknowledged uncertainties (e.g. cloud, misalignment, rgb_only)")
    limitations: List[str] = Field(default_factory=list, description="Operational or sensor limitations")
    model_name: str = Field(default="satquery-grounded-vlm", description="Name/identifier of the VLM reasoning engine used")
    reasoning_mode: str = Field(default="evidence_grounded", description="Mode of reasoning (e.g. deterministic_grounded, vlm_generative, fallback)")
